
thumbnailsDictionary = {
    'vim':'vim',
    'nvim':'nvim',
    'html': 'html',
    'css': 'css',
    'js': 'javascript',
    'php': 'php',
    'scss': 'sass',
    'py': 'python',
    'rs': 'rust',
    'c': 'c',
    'h': 'c',
    'cpp': 'cpp',
    'hpp': 'cpp',
    'cxx': 'cpp',
    'cc': 'cpp',
    'cs': 'c_sharp',
    'java': 'java',
    'md': 'md',
    'ts': 'typescript',
    'go': 'golang',
    'kt': 'kotlin',
    'kts': 'kotlin',
    'rb': 'ruby',
    'clj': 'clojure',
    'hs': 'haskell',
    'json': 'json',
    'vue': 'vue',
    'swift': 'swift',
    'lua': 'lua',
    'jl': 'julia',
    'dart': 'dart',

        }

